// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	DeleteURL(ctx context.Context, id int64) error
	GetURL(ctx context.Context, shortUrl string) (Url, error)
	UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error)
}

var _ Querier = (*Queries)(nil)
